-- SERÓN GROUNDS · Tratamientos de palmeras
create table if not exists public.palm_treatments (
  id bigint generated by default as identity primary key,
  client text not null,
  phone text,
  address text,
  treatment_date date,
  next_treatment_date date not null,
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.palm_treatments enable row level security;

drop policy if exists "palm_treatments_read" on public.palm_treatments;
create policy "palm_treatments_read" on public.palm_treatments for select to anon using (true);

drop policy if exists "palm_treatments_insert" on public.palm_treatments;
create policy "palm_treatments_insert" on public.palm_treatments for insert to anon with check (true);

drop policy if exists "palm_treatments_update" on public.palm_treatments;
create policy "palm_treatments_update" on public.palm_treatments for update to anon using (true) with check (true);

drop policy if exists "palm_treatments_delete" on public.palm_treatments;
create policy "palm_treatments_delete" on public.palm_treatments for delete to anon using (true);
